server:
  port: 3344
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
spring:
  application:
    name: cloud-config-center
  cloud:
    server:
      git:
        uri: git@github.com:1824485758/springcloud-config.git
        #搜索目录
        search-paths:
          - springcloud-config
    #读取分支
    label: master
